"""Millennium Dawn country tag presets — ported from countryTags.ts."""
from dataclasses import dataclass


@dataclass(frozen=True)
class CountryTagPreset:
    tag: str
    name: str


MD_COUNTRY_TAGS: list[CountryTagPreset] = [
    CountryTagPreset(tag='ABK', name='Abkhazia'),
    CountryTagPreset(tag='ACE', name='Aceh'),
    CountryTagPreset(tag='ADJ', name='Adjara'),
    CountryTagPreset(tag='ADO', name='Andorra'),
    CountryTagPreset(tag='ADY', name='Adygea'),
    CountryTagPreset(tag='AFG', name='Afghanistan'),
    CountryTagPreset(tag='AFR', name='Armed Forces Revolutionary Council'),
    CountryTagPreset(tag='AGL', name='Angola'),
    CountryTagPreset(tag='ALA', name='Alawite State'),
    CountryTagPreset(tag='ALB', name='Albania'),
    CountryTagPreset(tag='ALG', name='Algeria'),
    CountryTagPreset(tag='ALT', name='Altai'),
    CountryTagPreset(tag='ANT', name='Antigua and Barbuda'),
    CountryTagPreset(tag='AQY', name='Al-Qaeda in Yemen'),
    CountryTagPreset(tag='ARA', name='Arabistan'),
    CountryTagPreset(tag='ARG', name='Argentina'),
    CountryTagPreset(tag='ARK', name='Rakhine State'),
    CountryTagPreset(tag='ARM', name='Armenia'),
    CountryTagPreset(tag='ARU', name='Russia (NATO Mandate - Arctic)'),
    CountryTagPreset(tag='ASK', name='Alaska'),
    CountryTagPreset(tag='ASL', name='Ansar Al-Sharia (Libya)'),
    CountryTagPreset(tag='AST', name='Australia'),
    CountryTagPreset(tag='ATC', name='Anbar Tribal Council (Iraq)'),
    CountryTagPreset(tag='AUS', name='Austria'),
    CountryTagPreset(tag='AWD', name='Al-Awda (Iraq)'),
    CountryTagPreset(tag='AZE', name='Azerbaijan'),
    CountryTagPreset(tag='BAH', name='Bahamas'),
    CountryTagPreset(tag='BAL', name='Anti-Balaka'),
    CountryTagPreset(tag='BAN', name='Bangladesh'),
    CountryTagPreset(tag='BAR', name='Barbados'),
    CountryTagPreset(tag='BAY', name='Bavaria'),
    CountryTagPreset(tag='BDA', name='Badakhshan'),
    CountryTagPreset(tag='BEL', name='Belgium'),
    CountryTagPreset(tag='BEN', name='Benin'),
    CountryTagPreset(tag='BFA', name='Burkina Faso'),
    CountryTagPreset(tag='BHR', name='Bahrain'),
    CountryTagPreset(tag='BHU', name='Bhutan'),
    CountryTagPreset(tag='BLC', name='Balochistan'),
    CountryTagPreset(tag='BLG', name='Belarus (Liberation)'),
    CountryTagPreset(tag='BLR', name='Belarus'),
    CountryTagPreset(tag='BLZ', name='Belize'),
    CountryTagPreset(tag='BOL', name='Bolivia'),
    CountryTagPreset(tag='BOS', name='Bosnia'),
    CountryTagPreset(tag='BOT', name='Botswana'),
    CountryTagPreset(tag='BOZ', name='Iraq (BOZ)'),
    CountryTagPreset(tag='BRA', name='Brazil'),
    CountryTagPreset(tag='BRM', name='Burma'),
    CountryTagPreset(tag='BRU', name='Brunei'),
    CountryTagPreset(tag='BRY', name='Buryatia'),
    CountryTagPreset(tag='BSH', name='Bashkiria'),
    CountryTagPreset(tag='BUL', name='Bulgaria'),
    CountryTagPreset(tag='BUR', name='Burundi'),
    CountryTagPreset(tag='C01', name='Custom_01'),
    CountryTagPreset(tag='CAB', name='Cabinda'),
    CountryTagPreset(tag='CAL', name='California'),
    CountryTagPreset(tag='CAM', name='Cameroon'),
    CountryTagPreset(tag='CAN', name='Canada'),
    CountryTagPreset(tag='CAR', name='Central African Republic'),
    CountryTagPreset(tag='CAS', name='Cascadia'),
    CountryTagPreset(tag='CAT', name='Catalonia'),
    CountryTagPreset(tag='CBD', name='Cambodia'),
    CountryTagPreset(tag='CDI', name="Cote D'Ivoire"),
    CountryTagPreset(tag='CHA', name='Chad'),
    CountryTagPreset(tag='CHE', name='Chechnya'),
    CountryTagPreset(tag='CHI', name='China'),
    CountryTagPreset(tag='CHL', name='Chile'),
    CountryTagPreset(tag='CHS', name='Chin State'),
    CountryTagPreset(tag='CHU', name='Chuvashia'),
    CountryTagPreset(tag='CKK', name='Chukotka'),
    CountryTagPreset(tag='CNG', name='Congo'),
    CountryTagPreset(tag='CNR', name='Canary Islands'),
    CountryTagPreset(tag='COL', name='Colombia'),
    CountryTagPreset(tag='COM', name='Comoros'),
    CountryTagPreset(tag='COS', name='Costa Rica'),
    CountryTagPreset(tag='CRE', name='Crete'),
    CountryTagPreset(tag='CRM', name='Crimea'),
    CountryTagPreset(tag='CRO', name='Croatia'),
    CountryTagPreset(tag='CSA', name='Confederate States'),
    CountryTagPreset(tag='CSB', name='Central Siberia'),
    CountryTagPreset(tag='CSM', name='Casamance'),
    CountryTagPreset(tag='CUB', name='Cuba'),
    CountryTagPreset(tag='CYP', name='Cyprus'),
    CountryTagPreset(tag='CYR', name='Cyrenaica'),
    CountryTagPreset(tag='CZE', name='Czech Republic'),
    CountryTagPreset(tag='D01', name='D01'),
    CountryTagPreset(tag='D02', name='D02'),
    CountryTagPreset(tag='D03', name='D03'),
    CountryTagPreset(tag='D04', name='D04'),
    CountryTagPreset(tag='D05', name='D05'),
    CountryTagPreset(tag='D06', name='D06'),
    CountryTagPreset(tag='D07', name='D07'),
    CountryTagPreset(tag='D08', name='D08'),
    CountryTagPreset(tag='D09', name='D09'),
    CountryTagPreset(tag='D10', name='D10'),
    CountryTagPreset(tag='D11', name='D11'),
    CountryTagPreset(tag='D12', name='D12'),
    CountryTagPreset(tag='D13', name='D13'),
    CountryTagPreset(tag='D14', name='D14'),
    CountryTagPreset(tag='D15', name='D15'),
    CountryTagPreset(tag='D16', name='D16'),
    CountryTagPreset(tag='D17', name='D17'),
    CountryTagPreset(tag='D18', name='D18'),
    CountryTagPreset(tag='D19', name='D19'),
    CountryTagPreset(tag='D20', name='D20'),
    CountryTagPreset(tag='D21', name='D21'),
    CountryTagPreset(tag='D22', name='D22'),
    CountryTagPreset(tag='D23', name='D23'),
    CountryTagPreset(tag='D24', name='D24'),
    CountryTagPreset(tag='D25', name='D25'),
    CountryTagPreset(tag='D26', name='D26'),
    CountryTagPreset(tag='D27', name='D27'),
    CountryTagPreset(tag='D28', name='D28'),
    CountryTagPreset(tag='D29', name='D29'),
    CountryTagPreset(tag='D30', name='D30'),
    CountryTagPreset(tag='D31', name='D31'),
    CountryTagPreset(tag='D32', name='D32'),
    CountryTagPreset(tag='D33', name='D33'),
    CountryTagPreset(tag='D34', name='D34'),
    CountryTagPreset(tag='D35', name='D35'),
    CountryTagPreset(tag='D36', name='D36'),
    CountryTagPreset(tag='D37', name='D37'),
    CountryTagPreset(tag='D38', name='D38'),
    CountryTagPreset(tag='D39', name='D39'),
    CountryTagPreset(tag='D40', name='D40'),
    CountryTagPreset(tag='D41', name='D41'),
    CountryTagPreset(tag='D42', name='D42'),
    CountryTagPreset(tag='D43', name='D43'),
    CountryTagPreset(tag='D44', name='D44'),
    CountryTagPreset(tag='D45', name='D45'),
    CountryTagPreset(tag='D46', name='D46'),
    CountryTagPreset(tag='D47', name='D47'),
    CountryTagPreset(tag='D48', name='D48'),
    CountryTagPreset(tag='D49', name='D49'),
    CountryTagPreset(tag='D50', name='D50'),
    CountryTagPreset(tag='D51', name='D51'),
    CountryTagPreset(tag='D52', name='D52'),
    CountryTagPreset(tag='D53', name='D53'),
    CountryTagPreset(tag='D54', name='D54'),
    CountryTagPreset(tag='D55', name='D55'),
    CountryTagPreset(tag='D56', name='D56'),
    CountryTagPreset(tag='D57', name='D57'),
    CountryTagPreset(tag='D58', name='D58'),
    CountryTagPreset(tag='D59', name='D59'),
    CountryTagPreset(tag='D60', name='D60'),
    CountryTagPreset(tag='D61', name='D61'),
    CountryTagPreset(tag='D62', name='D62'),
    CountryTagPreset(tag='D63', name='D63'),
    CountryTagPreset(tag='D64', name='D64'),
    CountryTagPreset(tag='D65', name='D65'),
    CountryTagPreset(tag='D66', name='D66'),
    CountryTagPreset(tag='D67', name='D67'),
    CountryTagPreset(tag='D68', name='D68'),
    CountryTagPreset(tag='D69', name='D69'),
    CountryTagPreset(tag='D70', name='D70'),
    CountryTagPreset(tag='D71', name='D71'),
    CountryTagPreset(tag='D72', name='D72'),
    CountryTagPreset(tag='D73', name='D73'),
    CountryTagPreset(tag='D74', name='D74'),
    CountryTagPreset(tag='D75', name='D75'),
    CountryTagPreset(tag='DAG', name='Dagestan'),
    CountryTagPreset(tag='DAR', name='Darfur'),
    CountryTagPreset(tag='DEN', name='Denmark'),
    CountryTagPreset(tag='DJI', name='Djibouti'),
    CountryTagPreset(tag='DMI', name='Dominica'),
    CountryTagPreset(tag='DOM', name='Dominican Republic'),
    CountryTagPreset(tag='DON', name='Don'),
    CountryTagPreset(tag='DPR', name='Donetsk'),
    CountryTagPreset(tag='DRC', name='Democratic Republic of the Congo'),
    CountryTagPreset(tag='DRP', name='Dnipro'),
    CountryTagPreset(tag='DRU', name='Druze State'),
    CountryTagPreset(tag='EBP', name='Egypt (Baathist Revolt)'),
    CountryTagPreset(tag='ECU', name='Ecuador'),
    CountryTagPreset(tag='EGU', name='Equatorial Guinea'),
    CountryTagPreset(tag='EGY', name='Egypt'),
    CountryTagPreset(tag='ELS', name='El Salvador'),
    CountryTagPreset(tag='ENG', name='United Kingdom'),
    CountryTagPreset(tag='ERI', name='Eritrea'),
    CountryTagPreset(tag='ESB', name='Eastern Siberia'),
    CountryTagPreset(tag='EST', name='Estonia'),
    CountryTagPreset(tag='ETH', name='Ethiopia'),
    CountryTagPreset(tag='ETK', name='East Turkestan'),
    CountryTagPreset(tag='EUU', name='EU'),
    CountryTagPreset(tag='FAO', name='Faroe Islands'),
    CountryTagPreset(tag='FAR', name='Far Eastern Republic'),
    CountryTagPreset(tag='FEZ', name='Fezzan'),
    CountryTagPreset(tag='FGU', name='French Guyana'),
    CountryTagPreset(tag='FIJ', name='Fiji'),
    CountryTagPreset(tag='FIN', name='Finland'),
    CountryTagPreset(tag='FLA', name='Florida'),
    CountryTagPreset(tag='FLN', name='Flanders'),
    CountryTagPreset(tag='FNC', name="Forces Nouvelles de Cote d'Ivoire"),
    CountryTagPreset(tag='FRA', name='France'),
    CountryTagPreset(tag='FSA', name='Free Syrian Army'),
    CountryTagPreset(tag='FYR', name='Macedonia'),
    CountryTagPreset(tag='GAB', name='Gabon'),
    CountryTagPreset(tag='GAD', name='Libya (Gaddafi)'),
    CountryTagPreset(tag='GAH', name='Ghana'),
    CountryTagPreset(tag='GAL', name='Galicia'),
    CountryTagPreset(tag='GAM', name='Gambia'),
    CountryTagPreset(tag='GEO', name='Georgia'),
    CountryTagPreset(tag='GER', name='Germany'),
    CountryTagPreset(tag='GGZ', name='Gagauzia'),
    CountryTagPreset(tag='GLC', name='Great Lakes Confederation'),
    CountryTagPreset(tag='GMC', name='General Military Council for Iraqi Revolutionaries'),
    CountryTagPreset(tag='GNA', name='Government of National Accord - Libya'),
    CountryTagPreset(tag='GNC', name='National Salvation Government - Libya'),
    CountryTagPreset(tag='GOR', name='Gorksaya Republic'),
    CountryTagPreset(tag='GRA', name='Grenada'),
    CountryTagPreset(tag='GRE', name='Greece'),
    CountryTagPreset(tag='GRL', name='Greenland'),
    CountryTagPreset(tag='GRN', name='Greenland (Independent)'),
    CountryTagPreset(tag='GUA', name='Guatemala'),
    CountryTagPreset(tag='GUB', name='Guinea Bissau'),
    CountryTagPreset(tag='GUI', name='Guinea'),
    CountryTagPreset(tag='GUY', name='Guyana'),
    CountryTagPreset(tag='HAI', name='Haiti'),
    CountryTagPreset(tag='HAM', name='Hamas'),
    CountryTagPreset(tag='HAZ', name='Hazaristan'),
    CountryTagPreset(tag='HEJ', name='Hejaz'),
    CountryTagPreset(tag='HEZ', name='Hezbollah'),
    CountryTagPreset(tag='HII', name='Hamas of Iraq'),
    CountryTagPreset(tag='HKG', name='Hong Kong'),
    CountryTagPreset(tag='HLS', name='Holy See'),
    CountryTagPreset(tag='HOL', name='Holland'),
    CountryTagPreset(tag='HON', name='Honduras'),
    CountryTagPreset(tag='HOR', name='House of Representatives - Libya'),
    CountryTagPreset(tag='HOU', name='Houthi Yemen'),
    CountryTagPreset(tag='HPR', name='Harkov'),
    CountryTagPreset(tag='HRM', name='Hormuz'),
    CountryTagPreset(tag='HUN', name='Hungary'),
    CountryTagPreset(tag='HUS', name='Azerbaijan (Husayncilar)'),
    CountryTagPreset(tag='HWI', name='Hawaii'),
    CountryTagPreset(tag='HZG', name='Herzegovina'),
    CountryTagPreset(tag='IAI', name='Islamic Army in Iraq'),
    CountryTagPreset(tag='ICE', name='Iceland'),
    CountryTagPreset(tag='IDH', name='Idaho'),
    CountryTagPreset(tag='IEK', name='Islamic Emirate of Kurdistan'),
    CountryTagPreset(tag='IKR', name='Iranian Kurdistan'),
    CountryTagPreset(tag='IND', name='Indonesia'),
    CountryTagPreset(tag='ING', name='Ingushetia'),
    CountryTagPreset(tag='IOM', name='Isle of Mann'),
    CountryTagPreset(tag='IRE', name='Ireland'),
    CountryTagPreset(tag='IRI', name='Iran (Islamic Republic)'),
    CountryTagPreset(tag='IRP', name='Tajikistan (Islamist Uprising)'),
    CountryTagPreset(tag='IRQ', name='Iraq'),
    CountryTagPreset(tag='IRR', name='Iraq (Civil War)'),
    CountryTagPreset(tag='IRS', name='Iraq (Sunni Revolt)'),
    CountryTagPreset(tag='ISI', name='Islamic State'),
    CountryTagPreset(tag='ISR', name='Israel'),
    CountryTagPreset(tag='ITA', name='Italy'),
    CountryTagPreset(tag='JAM', name='Jamaica'),
    CountryTagPreset(tag='JAP', name='Japan'),
    CountryTagPreset(tag='JBP', name='Jordan (Baathist Revolt)'),
    CountryTagPreset(tag='JOR', name='Jordan'),
    CountryTagPreset(tag='JUB', name='Jubaland'),
    CountryTagPreset(tag='KAC', name='Kachin'),
    CountryTagPreset(tag='KAE', name='Karelia'),
    CountryTagPreset(tag='KAM', name='Kamtapur'),
    CountryTagPreset(tag='KAN', name='Kansas'),
    CountryTagPreset(tag='KAR', name='Karen'),
    CountryTagPreset(tag='KAS', name='Kashmir'),
    CountryTagPreset(tag='KAZ', name='Kazakhstan'),
    CountryTagPreset(tag='KBK', name='Kabardino Balkaria'),
    CountryTagPreset(tag='KCC', name='Karachay Cherkessia'),
    CountryTagPreset(tag='KEN', name='Kenya'),
    CountryTagPreset(tag='KHA', name='Sikh State'),
    CountryTagPreset(tag='KHM', name='Khanty-Mansi'),
    CountryTagPreset(tag='KHS', name='Khakassia'),
    CountryTagPreset(tag='KIR', name='Kiribati'),
    CountryTagPreset(tag='KLM', name='Kalmykia'),
    CountryTagPreset(tag='KOM', name='Komi'),
    CountryTagPreset(tag='KOR', name='Korea'),
    CountryTagPreset(tag='KOS', name='Kosovo'),
    CountryTagPreset(tag='KRP', name='Karakalpakstan'),
    CountryTagPreset(tag='KSH', name='Kashubia'),
    CountryTagPreset(tag='KUB', name='Kuban'),
    CountryTagPreset(tag='KUR', name='Kurdistan'),
    CountryTagPreset(tag='KUW', name='Kuwait'),
    CountryTagPreset(tag='KYR', name='Kyrgyzstan'),
    CountryTagPreset(tag='LAD', name='Ladakh'),
    CountryTagPreset(tag='LAG', name='Latgale'),
    CountryTagPreset(tag='LAO', name='Laos'),
    CountryTagPreset(tag='LAT', name='Latvia'),
    CountryTagPreset(tag='LBA', name='Libya'),
    CountryTagPreset(tag='LEB', name='Lebanon'),
    CountryTagPreset(tag='LES', name='Lesotho'),
    CountryTagPreset(tag='LIB', name='Liberia'),
    CountryTagPreset(tag='LIC', name='Liechtenstein'),
    CountryTagPreset(tag='LIT', name='Lithuania'),
    CountryTagPreset(tag='LKT', name='Lakota'),
    CountryTagPreset(tag='LNA', name='Libyan National Army'),
    CountryTagPreset(tag='LOG', name='Logone'),
    CountryTagPreset(tag='LOR', name='Luristan'),
    CountryTagPreset(tag='LPR', name='Lugansk'),
    CountryTagPreset(tag='LRB', name='Libya (Rebels)'),
    CountryTagPreset(tag='LRP', name='Lviv'),
    CountryTagPreset(tag='LUR', name='Liberians United for Reconciliation and Democracy'),
    CountryTagPreset(tag='LUX', name='Luxembourg'),
    CountryTagPreset(tag='MAC', name='Macau'),
    CountryTagPreset(tag='MAD', name='Madagascar'),
    CountryTagPreset(tag='MAL', name='Mali'),
    CountryTagPreset(tag='MAN', name='Manipur'),
    CountryTagPreset(tag='MAR', name='Marshall Islands'),
    CountryTagPreset(tag='MAU', name='Mauritania'),
    CountryTagPreset(tag='MAY', name='Malaysia'),
    CountryTagPreset(tag='MDA', name='Iraq (Shia Revolt)'),
    CountryTagPreset(tag='MEG', name='Meghalaya State'),
    CountryTagPreset(tag='MEL', name='Mari El'),
    CountryTagPreset(tag='MEX', name='Mexico'),
    CountryTagPreset(tag='MIC', name='Micronesian Federation'),
    CountryTagPreset(tag='MLC', name='Movement for the Liberation of Congo'),
    CountryTagPreset(tag='MLD', name='Maldives'),
    CountryTagPreset(tag='MLR', name='Malorossiya'),
    CountryTagPreset(tag='MLT', name='Malta'),
    CountryTagPreset(tag='MLV', name='Moldova'),
    CountryTagPreset(tag='MLW', name='Malawi'),
    CountryTagPreset(tag='MNC', name='Monaco'),
    CountryTagPreset(tag='MNF', name='Multi-National Force - Iraq'),
    CountryTagPreset(tag='MNT', name='Montenegro'),
    CountryTagPreset(tag='MOJ', name='Iran (Mojahedin)'),
    CountryTagPreset(tag='MON', name='Mongolia'),
    CountryTagPreset(tag='MOR', name='Morocco'),
    CountryTagPreset(tag='MOT', name='Operation Target (Generic)'),
    CountryTagPreset(tag='MOV', name='Mordovia'),
    CountryTagPreset(tag='MOZ', name='Mozambique'),
    CountryTagPreset(tag='MRT', name='Mauritius'),
    CountryTagPreset(tag='NAM', name='Namibia'),
    CountryTagPreset(tag='NAU', name='Nauru'),
    CountryTagPreset(tag='NAV', name='Basque'),
    CountryTagPreset(tag='NCY', name='Northern Cyprus'),
    CountryTagPreset(tag='NEE', name='Nenets'),
    CountryTagPreset(tag='NEJ', name='Nejd'),
    CountryTagPreset(tag='NEN', name='New England'),
    CountryTagPreset(tag='NEP', name='Nepal'),
    CountryTagPreset(tag='NGR', name='Niger'),
    CountryTagPreset(tag='NHN', name='North Shan State'),
    CountryTagPreset(tag='NIC', name='Nicaragua'),
    CountryTagPreset(tag='NIG', name='Nigeria'),
    CountryTagPreset(tag='NKO', name='North Korea'),
    CountryTagPreset(tag='NKR', name='Artsakh'),
    CountryTagPreset(tag='NLA', name='Netherlands Antilles'),
    CountryTagPreset(tag='NOR', name='Norway'),
    CountryTagPreset(tag='NOV', name='Novorossiya'),
    CountryTagPreset(tag='NPM', name='Nepal Maoist'),
    CountryTagPreset(tag='NRU', name='Russia (NATO Mandate)'),
    CountryTagPreset(tag='NTR', name='1920 Revolution Brigades (Iraq)'),
    CountryTagPreset(tag='NUS', name='Al-Nusra'),
    CountryTagPreset(tag='NYK', name='New York'),
    CountryTagPreset(tag='NZL', name='New Zealand'),
    CountryTagPreset(tag='OMA', name='Oman'),
    CountryTagPreset(tag='OPR', name='Odessa'),
    CountryTagPreset(tag='PAK', name='Pakistan'),
    CountryTagPreset(tag='PAL', name='Palestine'),
    CountryTagPreset(tag='PAN', name='Panama'),
    CountryTagPreset(tag='PAP', name='Papua New Guinea'),
    CountryTagPreset(tag='PAR', name='Paraguay'),
    CountryTagPreset(tag='PAT', name='Patagonia'),
    CountryTagPreset(tag='PAU', name='Palau'),
    CountryTagPreset(tag='PER', name='Persia'),
    CountryTagPreset(tag='PHI', name='Philippines'),
    CountryTagPreset(tag='PKK', name='Kurdistan Workers Party'),
    CountryTagPreset(tag='PMR', name='Transnistria'),
    CountryTagPreset(tag='POL', name='Poland'),
    CountryTagPreset(tag='POR', name='Portugal'),
    CountryTagPreset(tag='POZ', name='Iraq (POZ)'),
    CountryTagPreset(tag='PRP', name='Podolia'),
    CountryTagPreset(tag='PRU', name='Peru'),
    CountryTagPreset(tag='PTR', name='Puerto Rico'),
    CountryTagPreset(tag='PUK', name='PUK Kurdistan'),
    CountryTagPreset(tag='PUN', name='Puntland'),
    CountryTagPreset(tag='QAT', name='Qatar'),
    CountryTagPreset(tag='QIM', name='Oman (QIM)'),
    CountryTagPreset(tag='QTF', name='Qatif'),
    CountryTagPreset(tag='QUE', name='Quebec'),
    CountryTagPreset(tag='RAH', name='Tajikistan (Civil War)'),
    CountryTagPreset(tag='RAJ', name='British Raj'),
    CountryTagPreset(tag='RCD', name='Rally for Congolese Democracy'),
    CountryTagPreset(tag='RGD', name='Rio Grande'),
    CountryTagPreset(tag='ROJ', name='Rojava'),
    CountryTagPreset(tag='ROM', name='Romania'),
    CountryTagPreset(tag='RSK', name='Republika Srpska'),
    CountryTagPreset(tag='RUS', name='Lokot Republic'),
    CountryTagPreset(tag='RWA', name='Rwanda'),
    CountryTagPreset(tag='RYU', name='Ryukyu'),
    CountryTagPreset(tag='SAF', name='South Africa'),
    CountryTagPreset(tag='SAG', name='Saudi Arabia (Alt)'),
    CountryTagPreset(tag='SAM', name='Samoa'),
    CountryTagPreset(tag='SAO', name='Sao Tome'),
    CountryTagPreset(tag='SAR', name='Sardinia'),
    CountryTagPreset(tag='SAU', name='Saudi Arabia'),
    CountryTagPreset(tag='SAZ', name='South Azerbaijan'),
    CountryTagPreset(tag='SBP', name='Syria (Baathist Revolt)'),
    CountryTagPreset(tag='SCL', name='Padania'),
    CountryTagPreset(tag='SCO', name='Scotland'),
    CountryTagPreset(tag='SEL', name='Seleka'),
    CountryTagPreset(tag='SEN', name='Senegal'),
    CountryTagPreset(tag='SER', name='Serbia'),
    CountryTagPreset(tag='SEY', name='Seychelles'),
    CountryTagPreset(tag='SHA', name='Sahrawi'),
    CountryTagPreset(tag='SHB', name='Al-Shabaab'),
    CountryTagPreset(tag='SHN', name='South Shan State'),
    CountryTagPreset(tag='SIA', name='Siam'),
    CountryTagPreset(tag='SIB', name='Siberian Republic'),
    CountryTagPreset(tag='SIE', name='Sierra Leone'),
    CountryTagPreset(tag='SIK', name='Sikkim State'),
    CountryTagPreset(tag='SIL', name='Silesia'),
    CountryTagPreset(tag='SIN', name='Singapore'),
    CountryTagPreset(tag='SLA', name='Sinaloa Cartel'),
    CountryTagPreset(tag='SLO', name='Slovakia'),
    CountryTagPreset(tag='SLV', name='Slovenia'),
    CountryTagPreset(tag='SMA', name='San Marino'),
    CountryTagPreset(tag='SML', name='Somaliland'),
    CountryTagPreset(tag='SNA', name='Somali National Alliance'),
    CountryTagPreset(tag='SOL', name='Solomon Islands'),
    CountryTagPreset(tag='SOM', name='Somalia'),
    CountryTagPreset(tag='SOO', name='South Ossetia'),
    CountryTagPreset(tag='SOV', name='Russia'),
    CountryTagPreset(tag='SPA', name='Andalucia'),
    CountryTagPreset(tag='SPL', name='Sao Paulo'),
    CountryTagPreset(tag='SPR', name='Spain'),
    CountryTagPreset(tag='SRI', name='Sri Lanka'),
    CountryTagPreset(tag='SRU', name='Russia (NATO Mandate - Southern)'),
    CountryTagPreset(tag='SSU', name='South Sudan'),
    CountryTagPreset(tag='STC', name='Yemen (Southern Transitional Council)'),
    CountryTagPreset(tag='STH', name='St Helena'),
    CountryTagPreset(tag='STK', name='St.Kitts and Nevis'),
    CountryTagPreset(tag='STL', name='St.Lucia'),
    CountryTagPreset(tag='STV', name='St.Vincent and the Grenadines'),
    CountryTagPreset(tag='SUD', name='Sudan'),
    CountryTagPreset(tag='SUL', name='Southern Brazil'),
    CountryTagPreset(tag='SUR', name='Suriname'),
    CountryTagPreset(tag='SWA', name='Swaziland'),
    CountryTagPreset(tag='SWE', name='Sweden'),
    CountryTagPreset(tag='SWI', name='Switzerland'),
    CountryTagPreset(tag='SWS', name='South West State of Somalia'),
    CountryTagPreset(tag='SYR', name='Syria'),
    CountryTagPreset(tag='TAB', name='Tabaristan'),
    CountryTagPreset(tag='TAI', name='Taiwan'),
    CountryTagPreset(tag='TAJ', name='Tajikistan'),
    CountryTagPreset(tag='TAL', name='Afghan Taliban'),
    CountryTagPreset(tag='TAM', name='Tamaulipas'),
    CountryTagPreset(tag='TAT', name='Tatarstan'),
    CountryTagPreset(tag='TEX', name='Texas'),
    CountryTagPreset(tag='TIB', name='Tibet'),
    CountryTagPreset(tag='TIE', name='Tibesti'),
    CountryTagPreset(tag='TIM', name='East Timor'),
    CountryTagPreset(tag='TJK', name='Tajik (Diaspora)'),
    CountryTagPreset(tag='TLS', name='Talishstan'),
    CountryTagPreset(tag='TNZ', name='Tanzania'),
    CountryTagPreset(tag='TOG', name='Togo'),
    CountryTagPreset(tag='TON', name='Tonga'),
    CountryTagPreset(tag='TRA', name='Transylvania'),
    CountryTagPreset(tag='TRC', name='Tierra Caliente'),
    CountryTagPreset(tag='TRI', name='Trinidad'),
    CountryTagPreset(tag='TRK', name='Turkmenistan'),
    CountryTagPreset(tag='TRP', name='Tripolitania'),
    CountryTagPreset(tag='TTP', name='Pakistani Taliban'),
    CountryTagPreset(tag='TUA', name='Tuaregs'),
    CountryTagPreset(tag='TUL', name='Tuvalu'),
    CountryTagPreset(tag='TUN', name='Tunisia'),
    CountryTagPreset(tag='TUR', name='Turkey'),
    CountryTagPreset(tag='TUV', name='Tuva'),
    CountryTagPreset(tag='UAE', name='United Arab Emirates'),
    CountryTagPreset(tag='UAF', name='United States of Africa'),
    CountryTagPreset(tag='UDM', name='Udmurtia'),
    CountryTagPreset(tag='UDT', name='Union of Deseret'),
    CountryTagPreset(tag='UGA', name='Uganda'),
    CountryTagPreset(tag='UIQ', name='Iraq (US Reinvasion)'),
    CountryTagPreset(tag='UKR', name='Ukraine'),
    CountryTagPreset(tag='UNI', name='UNITA'),
    CountryTagPreset(tag='URA', name='Ural Republic'),
    CountryTagPreset(tag='URG', name='Uruguay'),
    CountryTagPreset(tag='USA', name='United States of America'),
    CountryTagPreset(tag='USB', name='Free States of America'),
    CountryTagPreset(tag='UZB', name='Uzbekistan'),
    CountryTagPreset(tag='UZI', name='Uzbekistan (Islamist Uprising)'),
    CountryTagPreset(tag='VAN', name='Vanuatu'),
    CountryTagPreset(tag='VEN', name='Venezuela'),
    CountryTagPreset(tag='VER', name='Cape Verde'),
    CountryTagPreset(tag='VIE', name='Vietnam'),
    CountryTagPreset(tag='VLG', name='Venezuela (Liberation)'),
    CountryTagPreset(tag='VMT', name='Vermont'),
    CountryTagPreset(tag='VOJ', name='Vojvodina'),
    CountryTagPreset(tag='VRP', name='Volhynia'),
    CountryTagPreset(tag='VTB', name='Vitebsk'),
    CountryTagPreset(tag='WAA', name='Wa State'),
    CountryTagPreset(tag='WAG', name='Wagner'),
    CountryTagPreset(tag='WAS', name='Wales'),
    CountryTagPreset(tag='WLC', name='Wallachia'),
    CountryTagPreset(tag='WVA', name='West Virginia'),
    CountryTagPreset(tag='YAK', name='Yakutia'),
    CountryTagPreset(tag='YAM', name='Yamalo-Nenets'),
    CountryTagPreset(tag='YEM', name='Yemen'),
    CountryTagPreset(tag='YUC', name='Yucatan'),
    CountryTagPreset(tag='ZAM', name='Zambia'),
    CountryTagPreset(tag='ZAP', name='Zapatista'),
    CountryTagPreset(tag='ZIM', name='Zimbabwe'),
    CountryTagPreset(tag='ZOM', name='Zombies'),
]
