MD_FOCUS_FILTERS = [
    "FOCUS_FILTER_POLITICAL",
    "FOCUS_FILTER_ECONOMY",
    "FOCUS_FILTER_INDUSTRY",
    "FOCUS_FILTER_RESEARCH",
    "FOCUS_FILTER_FOREIGN_POLICY",
    "FOCUS_FILTER_ARMY",
    "FOCUS_FILTER_NAVY",
    "FOCUS_FILTER_AIR",
    "FOCUS_FILTER_STABILITY",
    "FOCUS_FILTER_WAR_SUPPORT",
    "FOCUS_FILTER_TRADE",
    "FOCUS_FILTER_CORRUPTION",
    "FOCUS_FILTER_EXPENDITURE",
]

MD_ICON_PRESETS = [
    "MEX_Mexican_government",
    "MEX_Economic_reform",
    "army_reform",
    "military_planning",
    "research",
    "research3",
    "support_democracy",
    "communism",
    "nationalist_administration",
    "align_to_mexico",
    "align_to_venezuela",
    "focus_trade_republic",
    "industry",
    "construct_infrastructure",
    "modern_fighter",
    "MEX_The_Mexican_navy",
    "nuclear_energy",
]

# Most common country-modifier keys used by MD ideas/national spirits — seeds
# the idea editor's modifier dropdown (still free-typable for any other key).
COMMON_IDEA_MODIFIERS = [
    "stability_factor",
    "political_power_factor",
    "political_power_gain",
    "war_support_factor",
    "research_speed_factor",
    "production_speed_buildings_factor",
    "consumer_goods_factor",
    "industrial_capacity_factory",
    "industrial_capacity_dockyard",
    "monthly_population",
    "conscription_factor",
    "democratic_drift",
    "communism_drift",
    "fascism_drift",
    "neutrality_drift",
    "nationalist_drift",
    "drift_defence_factor",
    "army_org_factor",
    "army_attack_factor",
    "army_defence_factor",
    "army_morale_factor",
    "max_planning",
    "training_time_army_factor",
    "justify_war_goal_time",
    "surrender_limit",
    "corruption_cost_factor",
    "tax_gain_multiplier_modifier",
    "social_cost_multiplier_modifier",
    "foreign_influence_defense_modifier",
]

MD_TECH_CATEGORIES = [
    "CAT_industry",
    "CAT_computing_tech",
    "CAT_land_doctrine",
    "CAT_inf_wep",
    "CAT_artillery",
    "CAT_afv",
    "CAT_apc",
    "CAT_ifv",
    "CAT_air_eqp",
    "CAT_air_doctrine",
    "CAT_cas",
    "CAT_heli",
    "CAT_drones",
    "CAT_aa",
    "CAT_naval_all",
    "CAT_corvette",
    "CAT_frigate",
    "CAT_sub",
    "CAT_naval_modules",
]
